---
title: "Lab work intro to R graphics"
author: "Kristen Lee"
date: "March 1, 2017"
output: md_document
---

```{r}
housing <- read.csv("Rgraphics/dataSets/landdata-states.csv")
head(housing[1:5])
```

```{r}
housing <- read.csv("Rgraphics/dataSets/landdata-states.csv")
head(housing[1:5])

hist(housing$Home.Value)
```

```{r}
library(ggplot2)
ggplot(housing, aes(x = Home.Value)) +
  geom_histogram()
```
```{r}
plot(Home.Value ~ Date,
     data=subset(housing, State == "MA"))
points(Home.Value ~ Date, col="red",
       data=subset(housing, State == "TX"))
legend(1975, 400000,
       c("MA", "TX"), title="State",
       col=c("black", "red"),
       pch=c(1, 1))
```
```{r}
ggplot(subset(housing, State %in% c("MA", "TX")),
       aes(x=Date,
           y=Home.Value,
           color=State))+
  geom_point()
```

```{r}
hp2001Q1 <- subset(housing, Date == 2001.25) 
ggplot(hp2001Q1, aes(y = Structure.Cost, x = Land.Value)) + geom_point()
```

```{r}
ggplot(hp2001Q1,
       aes(y = Structure.Cost, x = log(Land.Value))) +
  geom_point()

```

```{r}
hp2001Q1$pred.SC <- predict(lm(Structure.Cost ~ log(Land.Value), data = hp2001Q1))

p1 <- ggplot(hp2001Q1, aes(x = log(Land.Value), y = Structure.Cost))

p1 + geom_point(aes(color = Home.Value)) +
  geom_line(aes(y = pred.SC))
```
```{r}
p1 +
  geom_point(aes(color = Home.Value)) +
  geom_smooth()
```

```{r}
p1 + 
  geom_text(aes(label=State), size = 3)
```
```{r}
##install.packages("ggrepel") 
library("ggrepel")
p1 + geom_point() + geom_text_repel(aes(label=State), size = 3)
```
```{r}
p1 +
  geom_point(aes(size = 2),# incorrect! 2 is not a variable
             color="red") # this is fine -- all points red
```
```{r}
p1 + geom_point(aes(color=Home.Value, shape = region))
```


## Exercise I

```{r}
dat <- read.csv("Rgraphics/dataSets/EconomistData.csv")
head(dat)

```
## 1. 
```{r}

ggplot(dat, aes(x = CPI, y = HDI, size = HDI.Rank)) + geom_point()

```

## 2. 
```{r}

ggplot(dat, aes(x = CPI, y = HDI, size = HDI.Rank)) + geom_point(color = "blue")

```

## 3.
```{r}
ggplot(dat, size= 2, aes(x = CPI, y = HDI, size = HDI.Rank)) + geom_point(aes(color= Region))
```

## 4. 
```{r}
ggplot(dat, aes(x = CPI, y = HDI, size = HDI.Rank)) + geom_point(size=2)

```

## 5.
```{r}
ggplot(dat, aes(x = CPI, y = HDI, size = HDI.Rank)) + geom_point(aes(size = HDI.Rank))

```

```{r}
args(geom_histogram)
args(stat_bin)

p2 <- ggplot(housing, aes(x = Home.Value))
p2 + geom_histogram()


```

```{r}

p2 + geom_histogram(stat = "bin", binwidth=4000)

```

```{r}

housing.sum <- aggregate(housing["Home.Value"], housing["State"], FUN=mean)
rbind(head(housing.sum), tail(housing.sum))
```

```{r}

ggplot(housing.sum, aes(x=State, y=Home.Value)) + 
  geom_bar(stat="identity")

```


# Exercise 2

## 1.
```{r}


ggplot(dat, aes(x = CPI, y = HDI, size = HDI.Rank)) + geom_point() 

```

## 2.
```{r}

ggplot(dat, aes(x = CPI, y = HDI, size = HDI.Rank)) + geom_point() + geom_smooth()


```
## 3.
```{r}
ggplot(dat, aes(x = CPI, y = HDI, size = HDI.Rank)) + stat_smooth() + geom_point()

```
```{r}
ggplot(dat, aes(x = CPI, y = HDI, size = HDI.Rank)) + geom_point() + geom_smooth() + geom_line()

```

```{r}
p3 <- ggplot(housing, aes(x = State, y = Home.Price.Index)) + theme(legend.position="top",
axis.text=element_text(size = 6))
(p4 <- p3 + geom_point(aes(color = Date),
                       alpha = 0.5,
                       size = 1.5,
                       position = position_jitter(width = 0.25, height = 0)))
```
```{r}
p4 + scale_x_discrete(name="State Abbreviation") +
  scale_color_continuous(name="",
                         breaks = c(1976, 1994, 2013),
                         labels = c("'76", "'94", "'13"))

```

```{r}
p4 +
  scale_x_discrete(name="State Abbreviation") +
  scale_color_continuous(name="",
                         breaks = c(1976, 1994, 2013),
                         labels = c("'76", "'94", "'13"),
                         low = "blue", high = "red")

```

# Exercise 3

## #1.-3. 

```{r}
ggplot(dat, size= 2, aes(x = CPI, y = HDI, size = HDI.Rank)) + geom_point(aes(color= Region))+ scale_y_discrete(name="Human Development Index") + scale_x_discrete("Corruption Perception Index") + scale_color_manual(values = c("red", "white","blue","black","coral", "orange"))
                                                                                                   
```

```{r}

p5 <- ggplot(housing, aes(x = Date, y = Home.Value))
p5 + geom_line(aes(color = State))

```

```{r}
(p5 <- p5 + geom_line() +
   facet_wrap(~State, ncol = 10))
```
```{r}
p5 + theme_linedraw()
```

```{r}
p5 + theme_light()
```
```{r}
p5 + theme_minimal() +
  theme(text = element_text(color = "turquoise"))

```

```{r}

theme_new <- theme_bw() +
  theme(plot.background = element_rect(size = 1, color = "blue", fill = "black"),
        text=element_text(size = 12, family = "Serif", color = "ivory"),
        axis.text.y = element_text(colour = "purple"),
        axis.text.x = element_text(colour = "red"),
        panel.background = element_rect(fill = "pink"),
        strip.background = element_rect(fill = ("orange")))

p5 + theme_new
```
```{r}

library(dplyr)
library(tidyr)

housing.byyear <- aggregate(cbind(Home.Value, Land.Value) ~ Date, data = housing, mean)
ggplot(housing.byyear,
       aes(x=Date)) +
  geom_line(aes(y=Home.Value), color="red") +
  geom_line(aes(y=Land.Value), color="blue")
```

```{r}

home.land.byyear <- gather(housing.byyear,
                           value = "value",
                           key = "type",
                           Home.Value, Land.Value)
ggplot(home.land.byyear,
       aes(x=Date,
           y=value,
           color=type)) +
  geom_line()

```
# Putting it all together

## was able to get like a quarter of it, then had to use google for help

```{r}

(pc2 <- pc1 + geom_smooth(aes(group = 1), method = "lm", formula = y ~ log(x), se = FALSE, color = "red")) + geom_point()
  
  
df2 <- data.frame(x = 1:5 , y = 1:25, z = 1:25)
s <- ggplot(df2, aes(x = x, y = y))
s + geom_point(aes(shape = z), size = 4) + scale_shape_identity()
 
 s + geom_point(aes(shape = z), size = 4, colour = "Red") +
    scale_shape_identity()
s + geom_point(aes(shape = z), size = 4, colour = "Red", fill = "Black") +
    scale_shape_identity()
  
  df2 <- data.frame(x = 1:5 , y = 1:25, z = 1:25)
  s <- ggplot(df2, aes(x = x, y = y))
  s + geom_point(aes(shape = z), size = 4) + scale_shape_identity()
  
  s + geom_point(aes(shape = z), size = 4, colour = "Red") +
    scale_shape_identity()
  s + geom_point(aes(shape = z), size = 4, colour = "Red", fill = "Black") +
    scale_shape_identity()

pc2 +
    geom_point(shape = 1, size = 4)


(pc3 <- pc2 +
     geom_point(size = 4.5, shape = 1) +
     geom_point(size = 4, shape = 1) +
     geom_point(size = 3.5, shape = 1))

 pointsToLabel <- c("Russia", "Venezuela", "Iraq", "Myanmar", "Sudan", "Afghanistan", "Congo", "Greece", "Argentina", "Brazil", "India", "Italy", "China", "South Africa", "Spane",
 "Botswana", "Cape Verde", "Bhutan", "Rwanda", "France", "United States", "Germany", "Britain", "Barbados", "Norway", "Japan","New Zealand", "Singapore")

(pc4 <- pc3 + geom_text(aes(label = Country), color = "gray20", data = subset(dat, Country %in% pointsToLabel)))
```



```{r}

library("ggrepel")
pc3 + geom_text_repel(aes(label = Country),color = "gray20",data = subset(dat, Country %in% pointsToLabel), force = 10) 

dat$Region <- factor(dat$Region,levels = c("EU W. Europe", "Americas","Asia Pacific", "East EU Cemt Asia", "MENA", "SSA"),
labels = c("OECD","Americas","Asia &\nOceania", "Central &\nEastern Europe","Middle East &\nnorth Africa","Sub-Saharan\nAfrica"))

pc4$data <- dat
pc4

library(grid)
(pc5 <- pc4 + scale_x_continuous(name = "Corruption Perceptions Index, 2011 (10=least corrupt)", limits = c(.9, 10.5), breaks = 1:10) + scale_y_continuous(name = "Human Development Index, 2011 (1=Best)", limits = c(0.2, 1.0),
breaks = seq(0.2, 1.0, by = 0.1)) + scale_color_manual(name = "",values = c("#24576D", "#099DD7","#28AADC","#248E84", "#F2583F","#96503F")) +ggtitle("Corruption and Human development"))

  library(grid) 
  (pc6 <- pc5 + theme_minimal() + theme(text = element_text(color = "gray20"),legend.position = c("top"), legend.direction = "horizontal",legend.justification = 0.1, 
legend.text = element_text(size = 11, color = "gray10"), axis.text = element_text(face = "italic"), axis.title.x = element_text(vjust = -1), axis.title.y = element_text(vjust = 2), axis.ticks.y = element_blank(), axis.line = element_line(color = "gray40", size = 0.5), axis.line.y = element_blank(), panel.grid.major = element_line(color = "gray50", size = 0.5),panel.grid.major.x = element_blank()))



```







